#!/bin/bash

# genetic-19.x.x (Genetic Package Manager) #

# Copyright (c) 2014-2019 Antonio Cao (@burzumishi) #

# This is free software; 
# You have unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# genetic 19.x.x (Genetic Package Manager) #

# Load genetic Configuration Files and Setups #

GENETIC_CONF="/etc/genetic";
GENETIC_LIB="/usr/lib/genetic";

# Import genetic Main Config File #
source $GENETIC_CONF/genetic.conf;

# Import genetic Dinamic Config Files (conf.d) #
if test -d "$GENETIC_CONF/conf.d"; then
  CONFD=$(find $GENETIC_CONF/conf.d -iname "*.conf");
  for confd in $CONFD; do
    source $confd;
  done
fi;

# Load genetic Libraries #

# Load genetic Environment Definitions #
source $GENETIC_LIB/libgenetic-env;
source $GENETIC_LIB/libgenetic-i18n;

# Load genetic Logger Functions #
source $GENETIC_LIB/libgenetic-log;

# Load genetic Core Functions #
source $GENETIC_LIB/libgenetic;

# Load genetic environment debug #
source $GENETIC_LIB/libgenetic-debug;

# Load genetic Package Manager Functions #
source $GENETIC_LIB/libgenetic-db;
source $GENETIC_LIB/libgenetic-package;
source $GENETIC_LIB/libgenetic-source;
source $GENETIC_LIB/libgenetic-build;
source $GENETIC_LIB/libgenetic-packager;
source $GENETIC_LIB/libgenetic-uninstall;
source $GENETIC_LIB/libgenetic-install;
source $GENETIC_LIB/libgenetic-unpack;

# Load genetic Bootstrap Genuine system #
source $GENETIC_LIB/libgenetic-bootstrap;

# Start 'genetic' #

main "$@";

# End 'genetic' #
