#!/bin/bash

#########################
#                       #
# Genuine DNA 2009-2014 #
#                       #
#########################

set +h;
umask 022;

unset CFLAGS
unset CXXFLAGS

OPTIONS="$1";

# Directories
DNA_DIR=$(pwd); # DNA source directory
INC_DIR="$DNA_DIR/includes"; # Includes and tools directory
SRC_DIR="$DNA_DIR/sources"; # DNA Source Download directory
TMP_DIR="$DNA_DIR/tmp"; # Temp directory used for extract sources.
SYS_DIR="$DNA_DIR/system"; # Future Genuine GNU/Linux system directory.
LOG_DIR="$DNA_DIR/log"; # Log package build directory.
TOOLBOX_DIR="$SYS_DIR/dnatools"; # DNA Build tools directory.
CROSSTOOLBOX_DIR="$SYS_DIR/dnacrosstools"; # DNA Build tools directory.
DNA_RULES="$INC_DIR/dna"; # Rules for build packages directory.
PATCH_DIR="$INC_DIR/dna.patch.files"; # Patches for build packages.

# DNA ToolBox
TOOLBOX="/dnatools";
CROSSTOOLBOX="/dnacrosstools";

PATH=$TOOLBOX/bin:$CROSSTOOLBOX/bin:/bin:/usr/bin

# Package & Patches Files
DNA_PACKAGES_LST=$(grep -v ^# $INC_DIR/dna.packages);
DNA_PATCHES_LST=$(grep -v ^# $INC_DIR/dna.patches);

# DNA Utilities
EXTRACT="$INC_DIR/dna.extract";

# DNA Legend
INF=" ** [inf]";
WRN=" !! [wrn]";
BLD=" ** [bld]";
ERR=" !! [ERR]";
DBG=" %% [dbg]";

# DNA Set Environment

ARCH=$(uname -m);

LC_ALL=POSIX

GENUINE_HOST=$(echo ${MACHTYPE} | sed -e 's/-[^-]*/-crossgenuine/')

GENUINE_TGT=""
GENUINE_TGT32="i686-pc-linux-gnu"
GENUINE_TGT64="x86_64-genuine-linux-gnu"

BUILD="";
BUILD32="-m32";
BUILD64="-m64";

case $(uname -m) in
        i?86) BUILD="$BUILD32";
		GENUINE_TGT="$GENUINE_TGT32";
        ;;
        x86_64) BUILD="$BUILD64";
		GENUINE_TGT="$GENUINE_TGT64";
        ;;
esac

export LC_ALL GENUINE_TGT GENUINE_TGT64 GENUINE_TGT32 GENUINE_HOST BUILD32 BUILD64 ARCH BUILD
export DNA_DIR INC_DIR SRC_DIR TMP_DIR SYS_DIR LOG_DIR TOOLBOX_DIR CROSSTOOLBOX_DIR DNA_RULES PATCH_DIR
export DNA_PACKAGES_LST DNA_PATCHES_LST TOOLBOX CROSSTOOLBOX PATH EXTRACT INF WRN BLD ERR DBG

# DNA Help
function dnahelp {
	echo "";
	echo "./dna build";
	echo "      clean";
	echo "      cleanall";
	echo "      debug";
	echo "";
}

# DNA DEBUG
function dna_dbg {
	echo ""
	echo "$DBG LC_ALL = $LC_ALL";
	echo "$DBG GENUINE_TGT = $GENUINE_TGT";
	echo "$DBG GENUINE_TGT64 = $GENUINE_TGT64";
	echo "$DBG GENUINE_TGT32 = $GENUINE_TGT32";
	echo "$DBG BUILD = $BUILD";
	echo "$DBG BUILD32 = $BUILD32";
	echo "$DBG BUILD64 = $BUILD64";
	echo "$DBG GENUINE_HOST = $GENUINE_HOST";
	echo "$DBG ARCH = $ARCH";	
	echo "$DBG DNA_DIR = $DNA_DIR";
	echo "$DBG INC_DIR = $INC_DIR";
	echo "$DBG SRC_DIR = $SRC_DIR";
	echo "$DBG TMP_DIR = $TMP_DIR";
	echo "$DBG SYS_DIR = $SYS_DIR";
	echo "$DBG LOG_DIR = $LOG_DIR";
	echo "$DBG TOOLBOX_DIR = $TOOLBOX_DIR";
	echo "$DBG CROSSTOOLBOX_DIR = $CROSSTOOLBOX_DIR";
	echo "$DBG DNA_RULES = $DNA_RULES";
	echo "$DBG PATCH_DIR = $PATCH_DIR";
	echo "$DBG DNA_PACKAGES_LST = $DNA_PACKAGES_LST";
	echo "$DBG DNA_PATCHES_LST = $DNA_PATCHES_LST";
	echo "$DBG CFLAGS = $CFLAGS";
	echo "$DBG CXXFLAGS = $CXXFLAGS";
	echo "$DBG TOOLBOX = $TOOLBOX";
	echo "$DBG CROSSTOOLBOX = $CROSSTOOLBOX";
	echo "$DBG PATH = $PATH";
	echo "$DBG EXTRACT = $EXTRACT";
	echo "$DBG INF = $INF";
	echo "$DBG WRN = $WRN";
	echo "$DBG BLD = $BLD";
	echo "$DBG ERR = $ERR";
	echo "$DBG DBG = $DBG";
	echo ""
}

#DNA Intro

echo "";
echo "$INF Genuine DNA (c) 2009-2014";
echo ""
echo "$INF Genuine Developer Tools";
echo "";

# DNA Options

case "$OPTIONS" in
	build) bash $INC_DIR/dna.build;
	       bash $INC_DIR/dna.mount $SYS_DIR;
	;;
	debug) dna_dbg; exit;
	;;
	clean) rm -rvf $TOOLBOX $CROSSTOOLBOX $SYS_DIR/* $TMP_DIR/* $LOG_DIR/*; exit;
	;;
	cleanall) rm -rvf $TOOLBOX $CROSSTOOLBOX $SYS_DIR/* $TMP_DIR/* $LOG_DIR/* $SRC_DIR/*; exit;
	;;
	*) dnahelp; exit;
	;;
esac

echo "";
echo "$INF Now you will be promted to Genuine ToolBox to finish base installation.";
echo "";
echo "$INF Execute /usr/DNA/Bootstrap/bootstrap_genuine_base.sh & /usr/DNA/Bootstrap/bootstrap_genuine_packages.sh to continue with Genuine GNU/Linux base system installation.";
echo "";

chroot "$SYS_DIR" $TOOLBOX/bin/env -i \
    HOME=/root TERM="$TERM" PS1='\u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin:$TOOLBOX/bin:$TOOLBOX/sbin:$CROSSTOOLBOX/bin:$CROSSTOOLBOX/sbin \
    $TOOLBOX/bin/bash --login +h

echo "";
echo "$WRN Umounting filesystems.";
echo "";
bash $INC_DIR/dna.umount $SYS_DIR;
echo "";

unset DNA_DIR INC_DIR SRC_DIR TMP_DIR SYS_DIR LOG_DIR TOOLBOX_DIR CROSSTOOLBOX_DIR DNA_RULES PATCH_DIR
unset DNA_PACKAGES_LST DNA_PATCHES_LST TOOLBOX CROSSTOOLBOX PATH EXTRACT INFO WARN BLD ERROR

exit
